# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-09 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessAiSite_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 11, 12, 49, 29, 127723), max_length='50'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gamebourd',
            field=models.CharField(max_length=1000),
        ),
    ]
