# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-09 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessAiSite_app', '0002_auto_20170209_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 15, 45, 57, 295678), max_length='50'),
        ),
    ]
