# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-10 04:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessAiSite_app', '0003_auto_20170209_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activationcode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 10, 4, 49, 20, 96869), max_length='50'),
        ),
    ]
