# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-10 05:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessAiSite_app', '0004_auto_20170210_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 10, 5, 53, 56, 390543), max_length='50'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=0),
        ),
    ]
