# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-10 07:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessAiSite_app', '0005_auto_20170210_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 10, 7, 19, 3, 892458), max_length='50'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isActive',
            field=models.IntegerField(default=0),
        ),
    ]
