# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-10 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessAiSite_app', '0006_auto_20170210_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 10, 11, 53, 33, 814398), max_length='50'),
        ),
    ]
