# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-11 21:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessAiSite_app', '0008_auto_20170211_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 11, 21, 6, 54, 409436), max_length='50'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gameboard',
            field=models.CharField(max_length=100),
        ),
    ]
