# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-11 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessAiSite_app', '0010_auto_20170211_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='playersturn',
        ),
        migrations.AlterField(
            model_name='user',
            name='activationcode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 11, 21, 12, 48, 950387), max_length='50'),
        ),
    ]
